modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="nameless_cat"
version="1.0"
displayName="Nameless Cat mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="nameless_cat.jpg"
credits="Silly Silver"
authors="Silly Silver"
description='''
Nameless Cat mod is based on the game "Nameless Cat"
'''